import PlantUMLEncoder from 'plantuml-encoder';

export class SimpleHTMLReportGenerator {
    static generate(analysis, title = 'JS2UML Architecture Report') {
        const { classes, relationships, insights, uml } = analysis;
        
        // ENCODE THE PLANTUML - THIS IS THE KEY!
        const encodedUML = PlantUMLEncoder.encode(uml);
        const plantUMLImageUrl = `https://www.plantuml.com/plantuml/svg/${encodedUML}`;
        const plantUMLEditorUrl = `https://www.plantuml.com/plantuml/umla/${encodedUML}`;
        
        return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .metrics { display: flex; gap: 20px; margin-bottom: 30px; }
        .metric { text-align: center; padding: 15px; background: #f5f5f5; border-radius: 8px; }
        .metric .value { font-size: 24px; font-weight: bold; color: #667eea; }
        .diagram { text-align: center; margin: 30px 0; }
        .plantuml-image { max-width: 100%; border: 1px solid #ddd; }
        .links { margin-top: 10px; }
        .links a { margin: 0 10px; padding: 8px 16px; background: #667eea; color: white; text-decoration: none; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🏗️ ${title}</h1>
        <p>Generated by Insight Suite JS2UML</p>
    </div>

    <div class="metrics">
        <div class="metric">
            <div class="value">${insights.totalClasses}</div>
            <div>Classes</div>
        </div>
        <div class="metric">
            <div class="value">${insights.totalMethods}</div>
            <div>Methods</div>
        </div>
        <div class="metric">
            <div class="value">${insights.qualityScore}%</div>
            <div>Quality</div>
        </div>
    </div>

    <div class="diagram">
        <h2>📐 Architecture Diagram</h2>
        <img src="${plantUMLImageUrl}" alt="PlantUML Diagram" class="plantuml-image">
        <div class="links">
            <a href="${plantUMLImageUrl}" target="_blank">🖼️ View Image</a>
            <a href="${plantUMLEditorUrl}" target="_blank">✏️ Open in Editor</a>
        </div>
    </div>

    <div>
        <h2>🏛️ Classes (${classes.length})</h2>
        ${classes.map(cls => `
            <div style="margin: 15px 0; padding: 15px; background: #f9f9f9; border-radius: 6px;">
                <h3>${cls.name}</h3>
                <p><strong>Methods:</strong> ${cls.methods.declared.join(', ')}</p>
                ${cls.properties.length > 0 ? `<p><strong>Properties:</strong> ${cls.properties.join(', ')}</p>` : ''}
            </div>
        `).join('')}
    </div>

    <div style="margin-top: 30px; padding: 15px; background: #f0f0f0; border-radius: 6px;">
        <h3>🔗 Encoded PlantUML URL</h3>
        <code style="word-break: break-all;">${plantUMLImageUrl}</code>
    </div>
</body>
</html>`;
    }
}
